name: 'Get Pull Request'
description: 'This action fetches a pull request based on simple inputs for use in non pull request triggers'

branding:
  icon: git-pull-request
  color: orange

inputs:
  pull-number:
    description: "The number of the pull request to fetch"
    required: true
    
outputs:
  pr:
    description: "The pull request, in JSON format"
    value: ${{ steps.get-pr.outputs.result }}

runs:
  using: "composite"
  steps:
    - uses: actions/github-script@v3
      id: get-pr
      with:
        script: |
          const request = {
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: inputs.pull-number
          };
          core.info(`Getting PR #${inputs.pull-number} from ${context.repo.owner}/${context.repo.repo}`);
          try {
            const result = await github.pulls.get(request);
            return result.data;
          } catch (err) {
            core.setFailed(`Request failed with error ${err}`);
          }
