name: "PR to Main"
on:
  pull_request:
    branches:
      - main

jobs:
  test-defaults: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./
        id: get-pr
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          
      - run: echo ${{ fromJSON(steps.get-pr.outputs.pr).title }}
      
      # Optionally fail the workflow, should you choose
      - name: Fail on failure
        if: ${{ fromJSON(steps.get-pr.outputs.pr).number != github.event.pull_request.number }}
        run: 'echo "Not Correct Answer :/" && exit 1'
        
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./
        id: get-pr
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pull-number: 1
          
      - run: echo ${{ fromJSON(steps.get-pr.outputs.pr).title }}
      
      # Optionally fail the workflow, should you choose
      - name: Fail on failure
        if: ${{ fromJSON(steps.get-pr.outputs.pr).number != 1 }}
        run: 'echo "Not Correct Answer :/" && exit 1'
        
  version-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: dkershner6/npm-version-check-with-comment-action@v1
        id: version-check
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - run: echo version changed -  ${{ steps.version-check.outputs.version-did-change }}
      
      - name: Fail on no version updated
        if: ${{ steps.version-check.outputs.version-did-change == 'false' }}
        run: 'echo "No version change :/" && exit 1'
  
  auto-approve-pr:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: hmarr/auto-approve-action@v2.0.0
        if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]' || github.actor == 'dkershner6'
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
